name: CI

on:
  pull_request:
  push:
    branches:
    - portable-python
  workflow_dispatch:
    inputs:
      verbose:
        required: false
        type: boolean

jobs:
  tests:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.9.21, 3.10.16, 3.11.11, 3.12.8, 3.13.1]
        os: [ubuntu]
        include:
          - os: ubuntu
            runner: ubuntu-latest

    name: ${{ matrix.os }}-${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13.1
      with:
        cmake-version: 3.13.5

    - name: Build
      run: |
        mkdir -p python-build && mkdir -p python-install
        cd python-build
        cmake \
          ${{ inputs.verbose && '--trace-expand --debug-find' || '' }} \
          -DCMAKE_INSTALL_PREFIX:PATH=${{ github.workspace }}/python-install \
          -DPYTHON_VERSION=${{ matrix.python-version }} \
          ..
        make -j4 ${{ inputs.verbose && 'VERBOSE=1' || '' }}
        make install

    - name: Check sysconfig
      run: |
        ./python-install/bin/python -m sysconfig

    - name: Test
      run: |
        ./python-install/bin/python -m ensurepip || true
        ./python-install/bin/python -m pip install certifi || true
        ./python-install/bin/python -m test -v --timeout 60 || true
